[programs.localnet]
gamble_match_escrow = "3YF3zQGgr1JpK1t9SXnLP9yLCbze3YHCmV1WNAG16pq3"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id4.json"

[scripts]
test = "mocha -t 1000000 tests/"
